# Tắt chế độ quét tất cả ngôn ngữ không mong muốn
sonar.scanner.scanAll=false

# Cấu hình đường dẫn file Coverage (Sửa lỗi "No data available")
sonar.cs.vscoveragexml.reportsPaths=**/TestResults/*.xml